// <auto-generated />
using CarWorldModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarWorldModel.Migrations
{
    [DbContext(typeof(Comp584MyCarDbContext))]
    [Migration("20250929193147_golden")]
    partial class golden
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarWorldModel.CarMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("make");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("origin");

                    b.HasKey("Id");

                    b.ToTable("CarMakes");
                });

            modelBuilder.Entity("CarWorldModel.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Acceleration")
                        .HasColumnType("float")
                        .HasColumnName("acceleration");

                    b.Property<int>("Cylinders")
                        .HasColumnType("int")
                        .HasColumnName("cylinders");

                    b.Property<double>("Displacement")
                        .HasColumnType("float")
                        .HasColumnName("displacement");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int")
                        .HasColumnName("horsepower");

                    b.Property<int>("MakeId")
                        .HasColumnType("int")
                        .HasColumnName("make_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int")
                        .HasColumnName("model_year");

                    b.Property<double>("Mpg")
                        .HasColumnType("float")
                        .HasColumnName("mpg");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("CarWorldModel.CarModel", b =>
                {
                    b.HasOne("CarWorldModel.CarMake", "Make")
                        .WithMany("CarModels")
                        .HasForeignKey("MakeId")
                        .IsRequired()
                        .HasConstraintName("FK_CarModels_CarMakes");

                    b.Navigation("Make");
                });

            modelBuilder.Entity("CarWorldModel.CarMake", b =>
                {
                    b.Navigation("CarModels");
                });
#pragma warning restore 612, 618
        }
    }
}
